//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace GameHelper.Resources
{
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings_DE
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings_DE()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GameHelper.Resources.Strings_DE", typeof(Strings_DE).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Schliessen.
        /// </summary>
        public static string CloseButtonTooltip
        {
            get
            {
                return ResourceManager.GetString("CloseButtonTooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Maximieren.
        /// </summary>
        public static string MaximizeButtonTooltip
        {
            get
            {
                return ResourceManager.GetString("MaximizeButtonTooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Minimieren.
        /// </summary>
        public static string MinimizeButtonTooltip
        {
            get
            {
                return ResourceManager.GetString("MinimizeButtonTooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string NavigationHome
        {
            get
            {
                return ResourceManager.GetString("NavigationHome", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Einstellungen.
        /// </summary>
        public static string NavigationSettings
        {
            get
            {
                return ResourceManager.GetString("NavigationSettings", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Suchen....
        /// </summary>
        public static string SearchFieldText
        {
            get
            {
                return ResourceManager.GetString("SearchFieldText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Willkommen.
        /// </summary>
        public static string WelcomeMessage
        {
            get
            {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
    }
}
